# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(815, 718)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 981, 711))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.Circle_button = QtGui.QPushButton(self.tab)
        self.Circle_button.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.Circle_button.setObjectName(_fromUtf8("Circle_button"))
        self.Line_button = QtGui.QPushButton(self.tab)
        self.Line_button.setGeometry(QtCore.QRect(20, 80, 75, 23))
        self.Line_button.setObjectName(_fromUtf8("Line_button"))
        self.Go_to_position_button = QtGui.QPushButton(self.tab)
        self.Go_to_position_button.setGeometry(QtCore.QRect(20, 140, 75, 23))
        self.Go_to_position_button.setObjectName(_fromUtf8("Go_to_position_button"))
        self.Grap_pen_button = QtGui.QPushButton(self.tab)
        self.Grap_pen_button.setGeometry(QtCore.QRect(20, 200, 75, 23))
        self.Grap_pen_button.setObjectName(_fromUtf8("Grap_pen_button"))
        self.Get_position_button = QtGui.QPushButton(self.tab)
        self.Get_position_button.setGeometry(QtCore.QRect(20, 260, 75, 23))
        self.Get_position_button.setObjectName(_fromUtf8("Get_position_button"))
        self.Reset_button = QtGui.QPushButton(self.tab)
        self.Reset_button.setGeometry(QtCore.QRect(20, 320, 75, 23))
        self.Reset_button.setObjectName(_fromUtf8("Reset_button"))
        self.Circle_R = QtGui.QSpinBox(self.tab)
        self.Circle_R.setGeometry(QtCore.QRect(140, 20, 42, 22))
        self.Circle_R.setMaximum(65535)
        self.Circle_R.setObjectName(_fromUtf8("Circle_R"))
        self.Circle_theta = QtGui.QSpinBox(self.tab)
        self.Circle_theta.setGeometry(QtCore.QRect(220, 20, 42, 22))
        self.Circle_theta.setMaximum(65535)
        self.Circle_theta.setObjectName(_fromUtf8("Circle_theta"))
        self.Line_R = QtGui.QSpinBox(self.tab)
        self.Line_R.setGeometry(QtCore.QRect(140, 80, 42, 22))
        self.Line_R.setMaximum(65535)
        self.Line_R.setObjectName(_fromUtf8("Line_R"))
        self.Line_theta = QtGui.QSpinBox(self.tab)
        self.Line_theta.setGeometry(QtCore.QRect(220, 80, 42, 22))
        self.Line_theta.setMaximum(65535)
        self.Line_theta.setObjectName(_fromUtf8("Line_theta"))
        self.Circle_T = QtGui.QSpinBox(self.tab)
        self.Circle_T.setGeometry(QtCore.QRect(300, 20, 42, 22))
        self.Circle_T.setMaximum(65535)
        self.Circle_T.setObjectName(_fromUtf8("Circle_T"))
        self.Position_X = QtGui.QSpinBox(self.tab)
        self.Position_X.setGeometry(QtCore.QRect(140, 140, 42, 22))
        self.Position_X.setMaximum(65535)
        self.Position_X.setObjectName(_fromUtf8("Position_X"))
        self.Position_Y = QtGui.QSpinBox(self.tab)
        self.Position_Y.setGeometry(QtCore.QRect(220, 140, 42, 22))
        self.Position_Y.setMaximum(65535)
        self.Position_Y.setObjectName(_fromUtf8("Position_Y"))
        self.Grap_pen_X = QtGui.QSpinBox(self.tab)
        self.Grap_pen_X.setGeometry(QtCore.QRect(140, 200, 42, 22))
        self.Grap_pen_X.setMaximum(65535)
        self.Grap_pen_X.setObjectName(_fromUtf8("Grap_pen_X"))
        self.Grap_pen_Y = QtGui.QSpinBox(self.tab)
        self.Grap_pen_Y.setGeometry(QtCore.QRect(220, 200, 42, 22))
        self.Grap_pen_Y.setMaximum(65535)
        self.Grap_pen_Y.setObjectName(_fromUtf8("Grap_pen_Y"))
        self.Get_position_display_X = QtGui.QLCDNumber(self.tab)
        self.Get_position_display_X.setGeometry(QtCore.QRect(140, 260, 91, 23))
        self.Get_position_display_X.setObjectName(_fromUtf8("Get_position_display_X"))
        self.Go_to_position_free = QtGui.QPushButton(self.tab)
        self.Go_to_position_free.setGeometry(QtCore.QRect(300, 140, 75, 23))
        self.Go_to_position_free.setObjectName(_fromUtf8("Go_to_position_free"))
        self.Grap_pen_free = QtGui.QPushButton(self.tab)
        self.Grap_pen_free.setGeometry(QtCore.QRect(300, 200, 75, 23))
        self.Grap_pen_free.setObjectName(_fromUtf8("Grap_pen_free"))
        self.Byte1 = QtGui.QSpinBox(self.tab)
        self.Byte1.setGeometry(QtCore.QRect(20, 490, 42, 22))
        self.Byte1.setMinimum(-1)
        self.Byte1.setMaximum(255)
        self.Byte1.setProperty("value", -1)
        self.Byte1.setObjectName(_fromUtf8("Byte1"))
        self.Byte2 = QtGui.QSpinBox(self.tab)
        self.Byte2.setGeometry(QtCore.QRect(70, 490, 42, 22))
        self.Byte2.setMinimum(-1)
        self.Byte2.setMaximum(255)
        self.Byte2.setSingleStep(1)
        self.Byte2.setProperty("value", -1)
        self.Byte2.setObjectName(_fromUtf8("Byte2"))
        self.Byte4 = QtGui.QSpinBox(self.tab)
        self.Byte4.setGeometry(QtCore.QRect(170, 490, 42, 22))
        self.Byte4.setMinimum(-1)
        self.Byte4.setMaximum(255)
        self.Byte4.setProperty("value", -1)
        self.Byte4.setObjectName(_fromUtf8("Byte4"))
        self.Byte3 = QtGui.QSpinBox(self.tab)
        self.Byte3.setGeometry(QtCore.QRect(120, 490, 42, 22))
        self.Byte3.setMinimum(-1)
        self.Byte3.setMaximum(255)
        self.Byte3.setProperty("value", -1)
        self.Byte3.setObjectName(_fromUtf8("Byte3"))
        self.Byte7 = QtGui.QSpinBox(self.tab)
        self.Byte7.setGeometry(QtCore.QRect(320, 490, 42, 22))
        self.Byte7.setMinimum(-1)
        self.Byte7.setMaximum(255)
        self.Byte7.setProperty("value", -1)
        self.Byte7.setObjectName(_fromUtf8("Byte7"))
        self.Byte8 = QtGui.QSpinBox(self.tab)
        self.Byte8.setGeometry(QtCore.QRect(370, 490, 42, 22))
        self.Byte8.setMinimum(-1)
        self.Byte8.setMaximum(255)
        self.Byte8.setProperty("value", -1)
        self.Byte8.setObjectName(_fromUtf8("Byte8"))
        self.Byte6 = QtGui.QSpinBox(self.tab)
        self.Byte6.setGeometry(QtCore.QRect(270, 490, 42, 22))
        self.Byte6.setMinimum(-1)
        self.Byte6.setMaximum(255)
        self.Byte6.setProperty("value", -1)
        self.Byte6.setObjectName(_fromUtf8("Byte6"))
        self.Byte5 = QtGui.QSpinBox(self.tab)
        self.Byte5.setGeometry(QtCore.QRect(220, 490, 42, 22))
        self.Byte5.setMinimum(-1)
        self.Byte5.setMaximum(255)
        self.Byte5.setProperty("value", -1)
        self.Byte5.setObjectName(_fromUtf8("Byte5"))
        self.Byte11 = QtGui.QSpinBox(self.tab)
        self.Byte11.setGeometry(QtCore.QRect(520, 490, 42, 22))
        self.Byte11.setMinimum(-1)
        self.Byte11.setMaximum(255)
        self.Byte11.setProperty("value", -1)
        self.Byte11.setObjectName(_fromUtf8("Byte11"))
        self.Byte12 = QtGui.QSpinBox(self.tab)
        self.Byte12.setGeometry(QtCore.QRect(570, 490, 42, 22))
        self.Byte12.setMinimum(-1)
        self.Byte12.setMaximum(255)
        self.Byte12.setProperty("value", -1)
        self.Byte12.setObjectName(_fromUtf8("Byte12"))
        self.Byte10 = QtGui.QSpinBox(self.tab)
        self.Byte10.setGeometry(QtCore.QRect(470, 490, 42, 22))
        self.Byte10.setMinimum(-1)
        self.Byte10.setMaximum(255)
        self.Byte10.setProperty("value", -1)
        self.Byte10.setObjectName(_fromUtf8("Byte10"))
        self.Byte9 = QtGui.QSpinBox(self.tab)
        self.Byte9.setGeometry(QtCore.QRect(420, 490, 42, 22))
        self.Byte9.setMinimum(-1)
        self.Byte9.setMaximum(255)
        self.Byte9.setProperty("value", -1)
        self.Byte9.setObjectName(_fromUtf8("Byte9"))
        self.Send_Package_button = QtGui.QPushButton(self.tab)
        self.Send_Package_button.setGeometry(QtCore.QRect(630, 490, 75, 23))
        self.Send_Package_button.setObjectName(_fromUtf8("Send_Package_button"))
        self.Serial_port_combo = QtGui.QComboBox(self.tab)
        self.Serial_port_combo.setGeometry(QtCore.QRect(520, 20, 131, 22))
        self.Serial_port_combo.setObjectName(_fromUtf8("Serial_port_combo"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(460, 20, 61, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.Connect_button = QtGui.QPushButton(self.tab)
        self.Connect_button.setGeometry(QtCore.QRect(670, 20, 75, 23))
        self.Connect_button.setObjectName(_fromUtf8("Connect_button"))
        self.Line_T = QtGui.QSpinBox(self.tab)
        self.Line_T.setGeometry(QtCore.QRect(300, 80, 42, 22))
        self.Line_T.setMaximum(65535)
        self.Line_T.setObjectName(_fromUtf8("Line_T"))
        self.Line_Y2 = QtGui.QSpinBox(self.tab)
        self.Line_Y2.setGeometry(QtCore.QRect(380, 80, 42, 22))
        self.Line_Y2.setMaximum(65535)
        self.Line_Y2.setObjectName(_fromUtf8("Line_Y2"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(150, 50, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(230, 50, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(310, 50, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(150, 110, 46, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(230, 110, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(310, 110, 46, 13))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(390, 110, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(150, 170, 46, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(230, 170, 46, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(230, 230, 46, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(150, 230, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.Get_position_display_Y = QtGui.QLCDNumber(self.tab)
        self.Get_position_display_Y.setGeometry(QtCore.QRect(250, 260, 91, 23))
        self.Get_position_display_Y.setObjectName(_fromUtf8("Get_position_display_Y"))
        self.Get_position_display_SW = QtGui.QLCDNumber(self.tab)
        self.Get_position_display_SW.setGeometry(QtCore.QRect(360, 260, 64, 23))
        self.Get_position_display_SW.setObjectName(_fromUtf8("Get_position_display_SW"))
        self.moveX_CW = QtGui.QPushButton(self.tab)
        self.moveX_CW.setGeometry(QtCore.QRect(20, 380, 75, 23))
        self.moveX_CW.setObjectName(_fromUtf8("moveX_CW"))
        self.breakX = QtGui.QPushButton(self.tab)
        self.breakX.setGeometry(QtCore.QRect(200, 380, 75, 23))
        self.breakX.setObjectName(_fromUtf8("breakX"))
        self.moveY_CW = QtGui.QPushButton(self.tab)
        self.moveY_CW.setGeometry(QtCore.QRect(20, 420, 75, 23))
        self.moveY_CW.setObjectName(_fromUtf8("moveY_CW"))
        self.breakY = QtGui.QPushButton(self.tab)
        self.breakY.setGeometry(QtCore.QRect(200, 420, 75, 23))
        self.breakY.setObjectName(_fromUtf8("breakY"))
        self.moveZ_up = QtGui.QPushButton(self.tab)
        self.moveZ_up.setGeometry(QtCore.QRect(290, 380, 75, 23))
        self.moveZ_up.setObjectName(_fromUtf8("moveZ_up"))
        self.breakZ = QtGui.QPushButton(self.tab)
        self.breakZ.setGeometry(QtCore.QRect(470, 380, 75, 23))
        self.breakZ.setObjectName(_fromUtf8("breakZ"))
        self.moveX_CCW = QtGui.QPushButton(self.tab)
        self.moveX_CCW.setGeometry(QtCore.QRect(110, 380, 75, 23))
        self.moveX_CCW.setObjectName(_fromUtf8("moveX_CCW"))
        self.moveY_CCW = QtGui.QPushButton(self.tab)
        self.moveY_CCW.setGeometry(QtCore.QRect(110, 420, 75, 23))
        self.moveY_CCW.setObjectName(_fromUtf8("moveY_CCW"))
        self.moveZ_down = QtGui.QPushButton(self.tab)
        self.moveZ_down.setGeometry(QtCore.QRect(380, 380, 75, 23))
        self.moveZ_down.setObjectName(_fromUtf8("moveZ_down"))
        self.breakAll = QtGui.QPushButton(self.tab)
        self.breakAll.setGeometry(QtCore.QRect(470, 420, 75, 23))
        self.breakAll.setObjectName(_fromUtf8("breakAll"))
        self.TunePID_button = QtGui.QPushButton(self.tab)
        self.TunePID_button.setGeometry(QtCore.QRect(460, 80, 75, 23))
        self.TunePID_button.setObjectName(_fromUtf8("TunePID_button"))
        self.TuneTrajX_button = QtGui.QPushButton(self.tab)
        self.TuneTrajX_button.setGeometry(QtCore.QRect(460, 140, 81, 23))
        self.TuneTrajX_button.setObjectName(_fromUtf8("TuneTrajX_button"))
        self.PID_Kp = QtGui.QSpinBox(self.tab)
        self.PID_Kp.setGeometry(QtCore.QRect(550, 80, 42, 22))
        self.PID_Kp.setMaximum(25500)
        self.PID_Kp.setObjectName(_fromUtf8("PID_Kp"))
        self.PID_Kd = QtGui.QSpinBox(self.tab)
        self.PID_Kd.setGeometry(QtCore.QRect(610, 80, 42, 22))
        self.PID_Kd.setMaximum(25500)
        self.PID_Kd.setObjectName(_fromUtf8("PID_Kd"))
        self.PID_Ki = QtGui.QSpinBox(self.tab)
        self.PID_Ki.setGeometry(QtCore.QRect(670, 80, 42, 22))
        self.PID_Ki.setMaximum(1000)
        self.PID_Ki.setObjectName(_fromUtf8("PID_Ki"))
        self.TrajX_Kp = QtGui.QSpinBox(self.tab)
        self.TrajX_Kp.setGeometry(QtCore.QRect(550, 140, 51, 22))
        self.TrajX_Kp.setMaximum(65535)
        self.TrajX_Kp.setObjectName(_fromUtf8("TrajX_Kp"))
        self.TrajX_Kd = QtGui.QSpinBox(self.tab)
        self.TrajX_Kd.setGeometry(QtCore.QRect(610, 140, 51, 22))
        self.TrajX_Kd.setMaximum(65535)
        self.TrajX_Kd.setObjectName(_fromUtf8("TrajX_Kd"))
        self.TrajX_Ki = QtGui.QSpinBox(self.tab)
        self.TrajX_Ki.setGeometry(QtCore.QRect(670, 140, 51, 22))
        self.TrajX_Ki.setMaximum(255)
        self.TrajX_Ki.setObjectName(_fromUtf8("TrajX_Ki"))
        self.TrajX_a = QtGui.QSpinBox(self.tab)
        self.TrajX_a.setGeometry(QtCore.QRect(730, 140, 51, 22))
        self.TrajX_a.setMaximum(65535)
        self.TrajX_a.setObjectName(_fromUtf8("TrajX_a"))
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(550, 110, 46, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(610, 110, 46, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(670, 110, 46, 13))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(550, 170, 46, 13))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(610, 170, 46, 13))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(670, 170, 46, 13))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(730, 170, 46, 13))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.PID_Yaxis = QtGui.QCheckBox(self.tab)
        self.PID_Yaxis.setGeometry(QtCore.QRect(720, 80, 70, 17))
        self.PID_Yaxis.setObjectName(_fromUtf8("PID_Yaxis"))
        self.pullButton = QtGui.QPushButton(self.tab)
        self.pullButton.setGeometry(QtCore.QRect(110, 320, 75, 23))
        self.pullButton.setObjectName(_fromUtf8("pullButton"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(200, 320, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.grapButton = QtGui.QPushButton(self.tab)
        self.grapButton.setGeometry(QtCore.QRect(290, 320, 75, 23))
        self.grapButton.setObjectName(_fromUtf8("grapButton"))
        self.degrapButton = QtGui.QPushButton(self.tab)
        self.degrapButton.setGeometry(QtCore.QRect(380, 320, 75, 23))
        self.degrapButton.setObjectName(_fromUtf8("degrapButton"))
        self.TrajY_Kd = QtGui.QSpinBox(self.tab)
        self.TrajY_Kd.setGeometry(QtCore.QRect(610, 190, 51, 22))
        self.TrajY_Kd.setMaximum(65535)
        self.TrajY_Kd.setObjectName(_fromUtf8("TrajY_Kd"))
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(550, 220, 46, 13))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.TuneTrajY_button = QtGui.QPushButton(self.tab)
        self.TuneTrajY_button.setGeometry(QtCore.QRect(460, 190, 81, 23))
        self.TuneTrajY_button.setObjectName(_fromUtf8("TuneTrajY_button"))
        self.TrajY_Ki = QtGui.QSpinBox(self.tab)
        self.TrajY_Ki.setGeometry(QtCore.QRect(670, 190, 51, 22))
        self.TrajY_Ki.setMaximum(255)
        self.TrajY_Ki.setObjectName(_fromUtf8("TrajY_Ki"))
        self.TrajY_a = QtGui.QSpinBox(self.tab)
        self.TrajY_a.setGeometry(QtCore.QRect(730, 190, 51, 22))
        self.TrajY_a.setMaximum(65535)
        self.TrajY_a.setObjectName(_fromUtf8("TrajY_a"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(730, 220, 46, 13))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(670, 220, 46, 13))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(610, 220, 46, 13))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.TrajY_Kp = QtGui.QSpinBox(self.tab)
        self.TrajY_Kp.setGeometry(QtCore.QRect(550, 190, 51, 22))
        self.TrajY_Kp.setMaximum(65535)
        self.TrajY_Kp.setObjectName(_fromUtf8("TrajY_Kp"))
        self.TrajCirX_Kp = QtGui.QSpinBox(self.tab)
        self.TrajCirX_Kp.setGeometry(QtCore.QRect(550, 240, 51, 22))
        self.TrajCirX_Kp.setMaximum(65535)
        self.TrajCirX_Kp.setObjectName(_fromUtf8("TrajCirX_Kp"))
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(670, 270, 46, 13))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.TrajCirX_Kd = QtGui.QSpinBox(self.tab)
        self.TrajCirX_Kd.setGeometry(QtCore.QRect(610, 240, 51, 22))
        self.TrajCirX_Kd.setMaximum(65535)
        self.TrajCirX_Kd.setObjectName(_fromUtf8("TrajCirX_Kd"))
        self.label_25 = QtGui.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(610, 270, 46, 13))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(730, 270, 46, 13))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.TrajCirX_a = QtGui.QSpinBox(self.tab)
        self.TrajCirX_a.setGeometry(QtCore.QRect(730, 240, 51, 22))
        self.TrajCirX_a.setMaximum(65535)
        self.TrajCirX_a.setObjectName(_fromUtf8("TrajCirX_a"))
        self.TuneCircle_buttonX = QtGui.QPushButton(self.tab)
        self.TuneCircle_buttonX.setGeometry(QtCore.QRect(460, 240, 81, 23))
        self.TuneCircle_buttonX.setObjectName(_fromUtf8("TuneCircle_buttonX"))
        self.label_27 = QtGui.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(550, 270, 46, 13))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.TrajCirX_Ki = QtGui.QSpinBox(self.tab)
        self.TrajCirX_Ki.setGeometry(QtCore.QRect(670, 240, 51, 22))
        self.TrajCirX_Ki.setMaximum(255)
        self.TrajCirX_Ki.setObjectName(_fromUtf8("TrajCirX_Ki"))
        self.TrajCirY_Ki = QtGui.QSpinBox(self.tab)
        self.TrajCirY_Ki.setGeometry(QtCore.QRect(670, 290, 51, 22))
        self.TrajCirY_Ki.setMaximum(255)
        self.TrajCirY_Ki.setObjectName(_fromUtf8("TrajCirY_Ki"))
        self.label_28 = QtGui.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(670, 320, 46, 13))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_30 = QtGui.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(730, 320, 46, 13))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(550, 320, 46, 13))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.TrajCirY_Kp = QtGui.QSpinBox(self.tab)
        self.TrajCirY_Kp.setGeometry(QtCore.QRect(550, 290, 51, 22))
        self.TrajCirY_Kp.setMaximum(65535)
        self.TrajCirY_Kp.setObjectName(_fromUtf8("TrajCirY_Kp"))
        self.TrajCirY_a = QtGui.QSpinBox(self.tab)
        self.TrajCirY_a.setGeometry(QtCore.QRect(730, 290, 51, 22))
        self.TrajCirY_a.setMaximum(65535)
        self.TrajCirY_a.setObjectName(_fromUtf8("TrajCirY_a"))
        self.TrajCirY_Kd = QtGui.QSpinBox(self.tab)
        self.TrajCirY_Kd.setGeometry(QtCore.QRect(610, 290, 51, 22))
        self.TrajCirY_Kd.setMaximum(65535)
        self.TrajCirY_Kd.setObjectName(_fromUtf8("TrajCirY_Kd"))
        self.label_29 = QtGui.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(610, 320, 46, 13))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.TuneCircle_buttonY = QtGui.QPushButton(self.tab)
        self.TuneCircle_buttonY.setGeometry(QtCore.QRect(460, 290, 81, 23))
        self.TuneCircle_buttonY.setObjectName(_fromUtf8("TuneCircle_buttonY"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.Load_camera_matrix_button = QtGui.QPushButton(self.tab_2)
        self.Load_camera_matrix_button.setGeometry(QtCore.QRect(10, 20, 161, 23))
        self.Load_camera_matrix_button.setObjectName(_fromUtf8("Load_camera_matrix_button"))
        self.Load_contour_button = QtGui.QPushButton(self.tab_2)
        self.Load_contour_button.setGeometry(QtCore.QRect(10, 60, 161, 23))
        self.Load_contour_button.setObjectName(_fromUtf8("Load_contour_button"))
        self.Line_option = QtGui.QRadioButton(self.tab_2)
        self.Line_option.setGeometry(QtCore.QRect(10, 100, 82, 17))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.Line_option.setFont(font)
        self.Line_option.setChecked(True)
        self.Line_option.setObjectName(_fromUtf8("Line_option"))
        self.Circle_option = QtGui.QRadioButton(self.tab_2)
        self.Circle_option.setGeometry(QtCore.QRect(10, 130, 82, 17))
        self.Circle_option.setObjectName(_fromUtf8("Circle_option"))
        self.Shape_option = QtGui.QRadioButton(self.tab_2)
        self.Shape_option.setGeometry(QtCore.QRect(10, 160, 151, 21))
        self.Shape_option.setObjectName(_fromUtf8("Shape_option"))
        self.camera_matrix_label = QtGui.QLabel(self.tab_2)
        self.camera_matrix_label.setGeometry(QtCore.QRect(190, 20, 411, 16))
        self.camera_matrix_label.setObjectName(_fromUtf8("camera_matrix_label"))
        self.contour_lebel = QtGui.QLabel(self.tab_2)
        self.contour_lebel.setGeometry(QtCore.QRect(190, 60, 411, 16))
        self.contour_lebel.setObjectName(_fromUtf8("contour_lebel"))
        self.Contour_option = QtGui.QRadioButton(self.tab_2)
        self.Contour_option.setGeometry(QtCore.QRect(10, 190, 82, 17))
        self.Contour_option.setObjectName(_fromUtf8("Contour_option"))
        self.Contour_infill = QtGui.QCheckBox(self.tab_2)
        self.Contour_infill.setGeometry(QtCore.QRect(120, 190, 70, 17))
        self.Contour_infill.setObjectName(_fromUtf8("Contour_infill"))
        self.Shape_infill = QtGui.QCheckBox(self.tab_2)
        self.Shape_infill.setGeometry(QtCore.QRect(120, 160, 70, 17))
        self.Shape_infill.setObjectName(_fromUtf8("Shape_infill"))
        self.start_button = QtGui.QPushButton(self.tab_2)
        self.start_button.setGeometry(QtCore.QRect(300, 20, 431, 181))
        font = QtGui.QFont()
        font.setPointSize(41)
        self.start_button.setFont(font)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.Test_option = QtGui.QRadioButton(self.tab_2)
        self.Test_option.setGeometry(QtCore.QRect(10, 220, 82, 17))
        self.Test_option.setObjectName(_fromUtf8("Test_option"))
        self.TestGripper_option = QtGui.QRadioButton(self.tab_2)
        self.TestGripper_option.setGeometry(QtCore.QRect(10, 250, 82, 17))
        self.TestGripper_option.setObjectName(_fromUtf8("TestGripper_option"))
        self.Shape_infill_2 = QtGui.QCheckBox(self.tab_2)
        self.Shape_infill_2.setGeometry(QtCore.QRect(120, 130, 70, 17))
        self.Shape_infill_2.setObjectName(_fromUtf8("Shape_infill_2"))
        self.TestCamMtx_option = QtGui.QRadioButton(self.tab_2)
        self.TestCamMtx_option.setGeometry(QtCore.QRect(10, 280, 141, 17))
        self.TestCamMtx_option.setObjectName(_fromUtf8("TestCamMtx_option"))
        self.kill_button = QtGui.QPushButton(self.tab_2)
        self.kill_button.setGeometry(QtCore.QRect(300, 220, 431, 181))
        font = QtGui.QFont()
        font.setPointSize(41)
        self.kill_button.setFont(font)
        self.kill_button.setObjectName(_fromUtf8("kill_button"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.Circle_button.setText(_translate("MainWindow", "Circle >>", None))
        self.Line_button.setText(_translate("MainWindow", "Line >>", None))
        self.Go_to_position_button.setText(_translate("MainWindow", "Go to >>", None))
        self.Grap_pen_button.setText(_translate("MainWindow", "Grap pen >>", None))
        self.Get_position_button.setText(_translate("MainWindow", "Get Pos >>", None))
        self.Reset_button.setText(_translate("MainWindow", "Reset >>", None))
        self.Go_to_position_free.setText(_translate("MainWindow", "Free Move", None))
        self.Grap_pen_free.setText(_translate("MainWindow", "Free Move", None))
        self.Send_Package_button.setText(_translate("MainWindow", "send>>", None))
        self.label_3.setText(_translate("MainWindow", "Serial port", None))
        self.Connect_button.setText(_translate("MainWindow", "Connect", None))
        self.label.setText(_translate("MainWindow", "R", None))
        self.label_2.setText(_translate("MainWindow", "theta", None))
        self.label_4.setText(_translate("MainWindow", "T", None))
        self.label_5.setText(_translate("MainWindow", "R", None))
        self.label_6.setText(_translate("MainWindow", "theta", None))
        self.label_7.setText(_translate("MainWindow", "T", None))
        self.label_8.setText(_translate("MainWindow", "y2", None))
        self.label_9.setText(_translate("MainWindow", "x", None))
        self.label_10.setText(_translate("MainWindow", "y", None))
        self.label_11.setText(_translate("MainWindow", "y", None))
        self.label_12.setText(_translate("MainWindow", "x", None))
        self.moveX_CW.setText(_translate("MainWindow", "MoveX CW", None))
        self.breakX.setText(_translate("MainWindow", "BreakX", None))
        self.moveY_CW.setText(_translate("MainWindow", "MoveY CW", None))
        self.breakY.setText(_translate("MainWindow", "BreakY", None))
        self.moveZ_up.setText(_translate("MainWindow", "MoveZ Up", None))
        self.breakZ.setText(_translate("MainWindow", "BreakZ", None))
        self.moveX_CCW.setText(_translate("MainWindow", "Move X CCW", None))
        self.moveY_CCW.setText(_translate("MainWindow", "MoveY CCW", None))
        self.moveZ_down.setText(_translate("MainWindow", "MoveZ Down", None))
        self.breakAll.setText(_translate("MainWindow", "Break All", None))
        self.TunePID_button.setText(_translate("MainWindow", "Tune PID>>", None))
        self.TuneTrajX_button.setText(_translate("MainWindow", "Tune TrajectX", None))
        self.label_13.setText(_translate("MainWindow", "Kp/100", None))
        self.label_14.setText(_translate("MainWindow", "Kd/100", None))
        self.label_15.setText(_translate("MainWindow", "Ki/100", None))
        self.label_16.setText(_translate("MainWindow", "Kp", None))
        self.label_17.setText(_translate("MainWindow", "Kd", None))
        self.label_18.setText(_translate("MainWindow", "Ki/100", None))
        self.label_19.setText(_translate("MainWindow", "a", None))
        self.PID_Yaxis.setText(_translate("MainWindow", "Y axis", None))
        self.pullButton.setText(_translate("MainWindow", "PULL>>", None))
        self.pushButton.setText(_translate("MainWindow", "PUSH>>", None))
        self.grapButton.setText(_translate("MainWindow", "GRAP>>", None))
        self.degrapButton.setText(_translate("MainWindow", "DEGRAP>>", None))
        self.label_20.setText(_translate("MainWindow", "Kp", None))
        self.TuneTrajY_button.setText(_translate("MainWindow", "Tune TrajectY", None))
        self.label_21.setText(_translate("MainWindow", "a", None))
        self.label_22.setText(_translate("MainWindow", "Ki/100", None))
        self.label_23.setText(_translate("MainWindow", "Kd", None))
        self.label_24.setText(_translate("MainWindow", "Ki/100", None))
        self.label_25.setText(_translate("MainWindow", "Kd", None))
        self.label_26.setText(_translate("MainWindow", "a", None))
        self.TuneCircle_buttonX.setText(_translate("MainWindow", "Tune CircleX", None))
        self.label_27.setText(_translate("MainWindow", "Kp", None))
        self.label_28.setText(_translate("MainWindow", "Ki/100", None))
        self.label_30.setText(_translate("MainWindow", "a", None))
        self.label_31.setText(_translate("MainWindow", "Kp", None))
        self.label_29.setText(_translate("MainWindow", "Kd", None))
        self.TuneCircle_buttonY.setText(_translate("MainWindow", "Tune CircleY", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1", None))
        self.Load_camera_matrix_button.setText(_translate("MainWindow", "Load camera matrix", None))
        self.Load_contour_button.setText(_translate("MainWindow", "Load contour", None))
        self.Line_option.setText(_translate("MainWindow", "Line", None))
        self.Circle_option.setText(_translate("MainWindow", "Circle", None))
        self.Shape_option.setText(_translate("MainWindow", "Shape with infill", None))
        self.camera_matrix_label.setText(_translate("MainWindow", "TextLabel", None))
        self.contour_lebel.setText(_translate("MainWindow", "TextLabel", None))
        self.Contour_option.setText(_translate("MainWindow", "Contour ", None))
        self.Contour_infill.setText(_translate("MainWindow", "Infill", None))
        self.Shape_infill.setText(_translate("MainWindow", "Infill", None))
        self.start_button.setText(_translate("MainWindow", "START!!!!", None))
        self.Test_option.setText(_translate("MainWindow", "test", None))
        self.TestGripper_option.setText(_translate("MainWindow", "test gripper", None))
        self.Shape_infill_2.setText(_translate("MainWindow", "Infill", None))
        self.TestCamMtx_option.setText(_translate("MainWindow", "test camera matrix", None))
        self.kill_button.setText(_translate("MainWindow", "KILL !!!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

